// LOCALHOST APP //-----------------------------------------------------
### get all contacts
GET http://localhost:3000/contacts

### get contact by ID
GET http://localhost:3000/contacts/626896030c00cba4d82973d1
### get contact by ID
GET http://localhost:3000/contacts/626897c50c00cba4d82973d2
### get contact by ID
GET http://localhost:3000/contacts/626897f80c00cba4d82973d3

### create new contact
POST http://localhost:3000/contacts HTTP/1.1
Content-Type: application/json

{
    "firstName": "D Lee",
    "lastName": "Tme",
    "email": "almost@gone.com",
    "favoriteColor": "black",
    "birthday": "01/01/1901",
    "number": "88",
    "party": "unknown",
    "term": "unknown"
}

### update contact by ID
PUT http://localhost:3000/contacts/62770e9bba6ecbf7b11c8293 HTTP/1.1
Content-Type: application/json

{
    "firstName": "Jane",
    "lastName": "Doe",
    "email": "jd2@notreal.com",
    "favoriteColor": "green",
    "birthday": "12/12/1912",
    "number": "99",
    "party": "what?",
    "term": "unknown"
}

### delete contact by ID
DELETE http://localhost:3000/contacts/62770e9bba6ecbf7b11c8293 HTTP/1.1


// HEROKU APP // -------------------------------------------------------
### get all contacts
GET https://cfowl-cse341.herokuapp.com/contacts

### get contact by ID
GET https://cfowl-cse341.herokuapp.com/contacts/626896030c00cba4d82973d1
### get contact by ID
GET https://cfowl-cse341.herokuapp.com/contacts/626897c50c00cba4d82973d2
### get contact by ID
GET https://cfowl-cse341.herokuapp.com/contacts/626897f80c00cba4d82973d3

### create new contact
POST http://cfowl-cse341.herokuapp.com/contacts HTTP/1.1
Content-Type: application/json

{
    "firstName": "Newell",
    "lastName": "User",
    "email": "hello@email.com",
    "favoriteColor": "white",
    "birthday": "10/10/1010",
    "number": "1",
    "party": "yes",
    "term": "what?"
}

### update contact by ID
PUT http://cfowl-cse341.herokuapp.com/contacts/62770e21ba6ecbf7b11c8292 HTTP/1.1
Content-Type: application/json

{
    "firstName": "Jane",
    "lastName": "Doe",
    "email": "jd2@notreal.com",
    "favoriteColor": "green",
    "birthday": "12/12/1912",
    "number": "2",
    "party": "no",
    "term": "limits"
}

### delete contact by ID
DELETE http://cfowl-cse341.herokuapp.com/contacts/627711c5cc800fd479e777ab HTTP/1.1

###